// Generates tiny base64 blur placeholders for the photographic images so
// next/image can render a blur-up while the full photo loads.
//
// Run with:  node scripts/generate-blur.mjs
// Output:    src/lib/blur-data.ts  (checked in)

import sharp from "sharp";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = "public/images";
const FILES = [
  "cave-exploring.jpg",
  "cave-formations.jpg",
  "cave-pool-research.jpg",
  "lab-bioreactor.jpg",
  "caco3-microscopy.jpg",
];

const map = {};
for (const file of FILES) {
  const buffer = await sharp(join(DIR, file))
    .resize(20) // tiny — the browser scales it up and blurs it
    .jpeg({ quality: 40 })
    .toBuffer();
  map[`/images/${file}`] = `data:image/jpeg;base64,${buffer.toString("base64")}`;
}

const out =
  "// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.\n" +
  "// Low-res base64 blur placeholders keyed by public image path.\n" +
  `export const blurData: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`;

writeFileSync("src/lib/blur-data.ts", out);
console.log(`Wrote ${Object.keys(map).length} blur placeholders to src/lib/blur-data.ts`);
